### ISSUE TITLE
s3-parallel-put needs a new maintainer

### ISSUE THREAD

**Issue by twpayne** [mishudark/s3-parallel-put#25]
I have not personally used `s3-parallel-put` for several years. Although I'm happy to merge pull requests, I do not have the time or resources to test them or do further development.

If you would like to take over maintenance of the project, please comment here and I'll give you write access to the repository.

**Comment by mishudark** [comment]
Hi, I would like to be a mantainer, I been contributed in others open source projects before, and this script  is in production in a large infraestructure with a few modification that I would like to integrate here

**Comment by twpayne** [comment]
Thanks mishudark@! I'll transfer the repository to you.

**Comment by mishudark** [comment]
Thanks :)

**Comment by twpayne** [comment]
Please approve the repository transfer.

**Comment by mishudark** [comment]
Hi, I don't have a transfer notification

**Comment by twpayne** [comment]
I've re-created the transfer and it looks like it was successful this time. Thanks!
