### ISSUE TITLE
Copy filename without directory structure

### ISSUE THREAD

**Issue by kjenney** [mishudark/s3-parallel-put#36]
I'm attempting to copy files from various subdirectories to the base of my S3 bucket. Here's an example:

`~/s3-parallel-put --bucket=mybackups --prefix /backups/12413412/mysql-backup/backups/myappdb-02/xtrabackups /mydb-server-01-backup-20160926-091734.tar.gz`

In this example I want the file mydb-server-01-backup-20160926-091734.tar.gz copied to the base of my bucket.

When I run s3-parallel-put I'm getting this:

`INFO:s3-parallel-put[statter-46529]:put 0 bytes in 0 files in 0.0 seconds (0 bytes/s, 0.0 files/s)`

Am I doing something wrong here?

**Comment by kjenney** [comment]
When I tried this:

`~/s3-parallel-put --bucket=mybackups /backups/12413412/mysql-backup/backups/myappdb-02/xtrabackups/mydb-server-01-backup-20160926-091734.tar.gz`

I got this error:

```
INFO:s3-parallel-put[statter-48310]:put 0 bytes in 0 files in 0.0 seconds (0 bytes/s, 0.0 files/s)
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/root/s3-parallel-put", line 273, in putter
    content = value.get_content()
  File "/root/s3-parallel-put", line 107, in get_content
    self.content = file_object.read()
MemoryError
INFO:s3-parallel-put[statter-48333]:put 0 bytes in 0 files in 0.1 seconds (0 bytes/s, 0.0 files/s)
```

**Comment by twpayne** [comment]
How large are your backup files? s3-parallel-put reads each file into memory before uploading it. It looks like you're running out of memory.

**Comment by kjenney** [comment]
That makes sense. The backups are very large (200G+). I'll end up forking my puts the old-fashioned way. Thanks!
